PACKAGE_NAME="zenbook_ec"
PACKAGE_VERSION="0.1.1"
MAKE[0]="make -C $kernel_source_dir M=$dkms_tree/$PACKAGE_NAME/$PACKAGE_VERSION/build"
CLEAN="make clean"
BUILT_MODULE_NAME[0]="zenbook_ec"
DEST_MODULE_LOCATION[0]="/kernel/drivers/platform/x86"
AUTOINSTALL="yes"